"""
Data Pipeline AI Agent for Cloud Data Agent Kit.
Generates, configures, and validates GCP data ingestion and ETL workflows.
"""

import logging
from typing import Dict, Any, Optional, List
from ..connectors.gcs_connector import GCSConnector
from ..connectors.bigquery_connector import BigQueryConnector
from ..config import DataAgentKitConfig

logger = logging.getLogger(__name__)


class DataPipelineAgent:
    """AI Agent responsible for automated ETL/ELT pipeline generation on GCP."""

    def __init__(self, config: Optional[DataAgentKitConfig] = None):
        self.config = config or DataAgentKitConfig()
        self.gcs_connector = GCSConnector(self.config.gcp)
        self.bq_connector = BigQueryConnector(self.config.gcp)

    def generate_gcs_to_bigquery_pipeline(
        self,
        source_gcs_prefix: str,
        destination_dataset: str,
        destination_table: str,
        file_format: str = "PARQUET",
    ) -> Dict[str, Any]:
        """Generate Python code / SQL definition for GCS -> BigQuery load job."""
        pipeline_code = f'''
# Generated by Cloud Data Agent Kit - DataPipelineAgent
from google.cloud import bigquery

def load_gcs_to_bq():
    client = bigquery.Client(project="{self.config.gcp.project_id}")
    dataset_ref = client.dataset("{destination_dataset}")
    table_ref = dataset_ref.table("{destination_table}")

    job_config = bigquery.LoadJobConfig()
    job_config.source_format = bigquery.SourceFormat.{file_format.upper()}
    job_config.write_disposition = bigquery.WriteDisposition.WRITE_APPEND
    job_config.autodetect = True

    uri = "gs://{self.config.gcp.gcs_bucket}/{source_gcs_prefix}*"
    load_job = client.load_table_from_uri(uri, table_ref, job_config=job_config)
    load_job.result()
    print(f"Loaded {{load_job.output_rows}} rows into {{table_ref.path}}")

if __name__ == "__main__":
    load_gcs_to_bq()
'''
        return {
            "pipeline_name": f"load_{source_gcs_prefix}_to_{destination_table}",
            "source": f"gs://{self.config.gcp.gcs_bucket}/{source_gcs_prefix}",
            "destination": f"{self.config.gcp.project_id}.{destination_dataset}.{destination_table}",
            "format": file_format,
            "pipeline_code": pipeline_code.strip(),
            "status": "generated",
        }

    def validate_pipeline_sources(self, source_prefix: str) -> Dict[str, Any]:
        """Check if source files exist in Cloud Storage before pipeline execution."""
        files = self.gcs_connector.list_files(prefix=source_prefix)
        return {
            "source_prefix": source_prefix,
            "files_found": len(files),
            "files": files,
            "valid": len(files) > 0,
        }
